name: Kyle

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore ./test/OpenFeature.IntegrationTests/

      - name: Build
        run: dotnet build ./test/OpenFeature.IntegrationTests/ -c Release --no-restore

      - name: Test
        run: |
          for i in {1..50}; do 
            dotnet test ./test/OpenFeature.IntegrationTests/ -c Release --no-build --logger "console;verbosity=detailed"
          done;
